version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./app.env
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./app.env
    ports:
      - "5050:80"
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '8000:8000'
    env_file:
      - ./app.env
    depends_on:
      - postgres
      - redis
volumes:
  redisDB:
  progresDB:
